// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_YbOupRpcqI7ptwgnLg83qoFXPCpn2Tc',
    appId: '1:992891783537:web:b0579fd3a246d04ba1ced0',
    messagingSenderId: '992891783537',
    projectId: 'amazonclone-sheikhnaveed',
    authDomain: 'clone-sheikhnaveed.firebaseapp.com',
    storageBucket: 'amazonclone-sheikhnaveed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsY1z_41fWGsepZS43z8WCy7CMU2BUFj4',
    appId: '1:992891783537:android:a1eab9ae43b4464ea1ced0',
    messagingSenderId: '992891783537',
    projectId: 'amazonclone-sheikhnaveed',
    storageBucket: 'amazonclone-sheikhnaveed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9c-iNYWi7-CfGmlum-kWHLEPP4UkQvG8',
    appId: '1:992891783537:ios:569af2e78a2cf2e0a1ced0',
    messagingSenderId: '992891783537',
    projectId: 'amazonclone-sheikhnaveed',
    storageBucket: 'amazonclone-sheikhnaveed.firebasestorage.app',
    iosBundleId: 'com.example.amazon',
  );
}
